/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = golf1052.YNABAPI.Client.SwaggerDateConverter;

namespace golf1052.YNABAPI.Model
{
    /// <summary>
    /// AccountsResponse
    /// </summary>
    [DataContract]
    public partial class AccountsResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccountsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsResponse" /> class.
        /// </summary>
        /// <param name="data">data (required).</param>
        public AccountsResponse(List<Account> accounts = default)
        {
            // to ensure "data" is required (not null)
            if (accounts == null)
            {
                throw new InvalidDataException("accounts is a required property for AccountsResponse and cannot be null");
            }
            else
            {
                this.Accounts = accounts;
            }
        }
        
        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="accounts", EmitDefaultValue=false)]
        public List<Account> Accounts { get; set; }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }

}
