/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = golf1052.YNABAPI.Client.SwaggerDateConverter;

namespace golf1052.YNABAPI.Model
{
    /// <summary>
    /// SaveMonthCategoryWrapper
    /// </summary>
    [DataContract]
    public partial class SaveMonthCategoryWrapper :  IEquatable<SaveMonthCategoryWrapper>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveMonthCategoryWrapper" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SaveMonthCategoryWrapper() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveMonthCategoryWrapper" /> class.
        /// </summary>
        /// <param name="category">category (required).</param>
        public SaveMonthCategoryWrapper(SaveMonthCategory category = default(SaveMonthCategory))
        {
            // to ensure "category" is required (not null)
            if (category == null)
            {
                throw new InvalidDataException("category is a required property for SaveMonthCategoryWrapper and cannot be null");
            }
            else
            {
                this.Category = category;
            }
        }
        
        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name="category", EmitDefaultValue=false)]
        public SaveMonthCategory Category { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SaveMonthCategoryWrapper {\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SaveMonthCategoryWrapper);
        }

        /// <summary>
        /// Returns true if SaveMonthCategoryWrapper instances are equal
        /// </summary>
        /// <param name="input">Instance of SaveMonthCategoryWrapper to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SaveMonthCategoryWrapper input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Category == input.Category ||
                    (this.Category != null &&
                    this.Category.Equals(input.Category))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                return hashCode;
            }
        }
    }

}
