/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = golf1052.YNABAPI.Client.SwaggerDateConverter;

namespace golf1052.YNABAPI.Model
{
    /// <summary>
    /// SaveTransactionWrapper
    /// </summary>
    [DataContract]
    public partial class SaveTransactionWrapper :  IEquatable<SaveTransactionWrapper>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveTransactionWrapper" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SaveTransactionWrapper() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveTransactionWrapper" /> class.
        /// </summary>
        /// <param name="transaction">transaction (required).</param>
        public SaveTransactionWrapper(SaveTransaction transaction = default(SaveTransaction))
        {
            // to ensure "transaction" is required (not null)
            if (transaction == null)
            {
                throw new InvalidDataException("transaction is a required property for SaveTransactionWrapper and cannot be null");
            }
            else
            {
                this.Transaction = transaction;
            }
        }
        
        /// <summary>
        /// Gets or Sets Transaction
        /// </summary>
        [DataMember(Name="transaction", EmitDefaultValue=false)]
        public SaveTransaction Transaction { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SaveTransactionWrapper {\n");
            sb.Append("  Transaction: ").Append(Transaction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SaveTransactionWrapper);
        }

        /// <summary>
        /// Returns true if SaveTransactionWrapper instances are equal
        /// </summary>
        /// <param name="input">Instance of SaveTransactionWrapper to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SaveTransactionWrapper input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Transaction == input.Transaction ||
                    (this.Transaction != null &&
                    this.Transaction.Equals(input.Transaction))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Transaction != null)
                    hashCode = hashCode * 59 + this.Transaction.GetHashCode();
                return hashCode;
            }
        }
    }

}
