/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = golf1052.YNABAPI.Client.SwaggerDateConverter;

namespace golf1052.YNABAPI.Model
{
    /// <summary>
    /// TransactionsResponse
    /// </summary>
    [DataContract]
    public partial class TransactionsResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionsResponse" /> class.
        /// </summary>
        /// <param name="data">data (required).</param>
        public TransactionsResponse(List<TransactionDetail> transactions = default)
        {
            // to ensure "data" is required (not null)
            if (transactions == null)
            {
                throw new InvalidDataException("data is a required property for TransactionsResponse and cannot be null");
            }
            else
            {
                this.Transactions = transactions;
            }
        }
        
        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name= "transactions", EmitDefaultValue=false)]
        public List<TransactionDetail> Transactions { get; set; }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}
